version: '3.9'
services:
  app:
    container_name: nest-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: ['yarn', 'start:dev']
# db:
#   container_name: postgres-db
#   image: postgres:15-alpine
#   ports:
#     - '5432:5432'
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: password
#     POSTGRES_DB: nest_docker
#   volumes:
#     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
